### ISSUE TITLE
Getting 500 Error when trying to hit the metrics endpoint

### ISSUE THREAD

**Issue by karthimohan** [bergerx/prom_marathon_app_exporter#3]
@bergerx I tried to the use the Docker image to pull the metrics from Marathon. container is running without any exceptions in the log. However when curl http://localhost:9099/metrics, i get the 500 error from Nginx. Could you please check and let me know what i am missing here

curl http://localhost:9099/metrics
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by bergerx** [comment]
Just tried the image in our cluster with this config, and still working, did you try cheking the logs of the container:
```
{
  "cpus": 0.01,
  "mem": 50,
  "id": "/marathon-app-exporter",
  "instances": 1,
  "env": {
    "MARATHON_URL": "http://leader.mesos:8080/"
  },
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "bergerx/prom-marathon-app-exporter",
      "network": "BRIDGE",
      "portMappings": [{"containerPort": 9099}]
    }
  },
  "labels": {
    "HAPROXY_0_VHOST": "marathon-app-exporter.test-cluster",
    "HAPROXY_GROUP": "external"
  },
  "healthChecks": [{"protocol": "HTTP", "path": "/metrics"}]
}
```

**Comment by karthimohan** [comment]
@bergerx I was able to get this working after I passed the login credentials to the URL. It worked with Marathon 1.1.1.

Now I am running Marathon 1.3.9 where they added authorization hooks for system endpoints. After this change, this app returns 500 even after I provide the login credentials via the MARATHON_URL.  I am able to curl and get the response using the events endpoint using the login credentials that i am using. Could you please check and let me know if this app needs any changes?

Authorization to system endpoints
Marathon already has authorization hooks for AppDefinition and Group changes.
We added authorization hooks for system endpoints: /v2/leader, /v2/info, /v2/events , /v2/eventSubscriptions.

When i run this curl inside the Marathon-app-Exporter container and i get the metrics back. Not sure if i need to modify something in Nginx. 

curl -XGET "http://leader.mesos:8080/metrics"

root@77590602fae8:/# tail -f /var/log/nginx/prom_marathon_app_exporter.access.log
172.17.42.1 - - [13/Feb/2017:23:43:30 +0000] "GET /metrics HTTP/1.1" 500 291 "-" "Go-http-client/1.1"
172.17.42.1 - - [13/Feb/2017:23:44:30 +0000] "GET /metrics HTTP/1.1" 500 291 "-" "Go-http-client/1.1"
172.17.42.1 - - [13/Feb/2017:23:45:30 +0000] "GET /metrics HTTP/1.1" 500 291 "-" "Go-http-client/1.1"
172.17.42.1 - - [13/Feb/2017:23:46:30 +0000] "GET /metrics HTTP/1.1" 500 291 "-" "Go-http-client/1.1"

**Comment by karthimohan** [comment]
@bergerx I was able to fix this issue after upgrading Marathon-Python Lib to 0.8.10.
